### ISSUE TITLE
[Bug]: Show StorageClass even if there are no requests

### ISSUE THREAD

**Issue by janlauber** [natron-io/tenant-dashboard#28]
### What happened?

atm. there will only be shown the storage class which has ressource allocated.
but when no ressource is allocated and quota > 0 is set it should be displayed also with 100% free.

### Version

v0.1.1

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by michaelmumenthaler** [comment]
Resolved in #29
