### ISSUE TITLE
Fix 4 Maintainability issues in src\App.tsx

### ISSUE THREAD

**Issue by janlauber** [natron-io/tenant-dashboard#3]
[CodeFactor](https://www.codefactor.io/repository/github/natron-io/tenant-dashboard/overview/base-ui-design) found multiple issues last seen at 38d90aa9973e8a10476b5e851130a8205071ddb1:

#### &#39;useEffect&#39; is defined but never used.
- [x]  [src\App.tsx:14](https://www.codefactor.io/repository/github/natron-io/tenant-dashboard/source/base-ui-design/src/App.tsx#L14)

#### &#39;useContext&#39; is defined but never used.
- [x]  [src\App.tsx:14](https://www.codefactor.io/repository/github/natron-io/tenant-dashboard/source/base-ui-design/src/App.tsx#L14)

#### &#39;createContext&#39; is defined but never used.
- [x]  [src\App.tsx:14](https://www.codefactor.io/repository/github/natron-io/tenant-dashboard/source/base-ui-design/src/App.tsx#L14)

#### &#39;Grid&#39; is defined but never used.
- [x]  [src\App.tsx:5](https://www.codefactor.io/repository/github/natron-io/tenant-dashboard/source/base-ui-design/src/App.tsx#L5)

**Comment by janlauber** [comment]
@michaelmumenthaler please fix these before merging.

**Comment by michaelmumenthaler** [comment]
Fixed
